apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt" # TLS requirement - enables cert-manager
spec:
  ingressClassName: nginx
  tls:                                    
  - hosts:                                
    - {{ .Values.domain.host }}                  
    secretName: {{ .Values.domain.host | replace "." "-" }}-tls  # TLS requirement - certificate stored here
  rules:
  - host: {{ .Values.domain.host }}
    http:
      paths:
      - path: {{ .Values.demo.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.demo.service.name }}
            port:
              number: {{ .Values.demo.service.port }}