apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    {{- if ne .Values.domain.host "localhost" }}
    cert-manager.io/issuer: "letsencrypt"  # TLS requirement - enables cert-manager
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  {{- if ne .Values.domain.host "localhost" }}
  tls:
    - hosts:
        - {{ .Values.domain.host }}
      secretName: {{ .Values.domain.host | replace "." "-" }}-tls  # TLS requirement - certificate stored here
  {{- end }}
  rules:
    - host: {{ .Values.domain.host }}
      http:
        paths:
          - path: {{ .Values.proxyd.ingress.rpcPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.proxyd.name }}-service
                port:
                  number: {{ .Values.proxyd.ports.rpc }}
          - path: {{ .Values.proxyd.ingress.wsPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.proxyd.name }}-service
                port:
                  number: {{ .Values.proxyd.ports.ws }}