apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.proxyd.name }}-env
  labels:
    app: {{ .Values.proxyd.name }}
data:
  proxyd.toml: |
    # proxyd.toml
    ws_method_whitelist = [
      "eth_subscribe",
      "eth_call",
      "eth_chainId",
      "eth_blocknumber"
    ]
    ws_backend_group = "main"

    [server]
    rpc_host = "0.0.0.0"
    rpc_port = {{ .Values.proxyd.ports.rpc }}
    ws_host = "0.0.0.0"
    ws_port = {{ .Values.proxyd.ports.ws }}
    max_body_size_bytes = 10485760
    max_concurrent_rpcs = 1000
    log_level = "info"

    [redis]
    url = "redis://{{ .Values.proxyd.redis.name }}-service:6379"

    [metrics]
    enabled = true
    host = "0.0.0.0" # kube-prometheus-stack:9090 # Check if we can make this name dynamic
    port = 9090 # 9090 or 9761

    [backend]
    response_timeout_seconds = 5
    max_response_size_bytes = 5242880
    max_retries = 3
    out_of_service_seconds = 600
    max_latency_threshold = "30s"
    max_degraded_latency_threshold = "10s"
    max_error_rate_threshold = 0.3

    [backends]
    [backends.sequencer]
    rpc_url = "http://{{ .Values.geth.name }}-sequencer-service:{{ .Values.geth.ports.rpc }}"
    ws_url = "ws://{{ .Values.geth.name }}-sequencer-service:{{ .Values.geth.ports.ws }}"
    max_rps = 10
    max_ws_conns = 5

    [backends.replicas]
    rpc_url = "http://{{ .Values.geth.name }}-replica-service:{{ .Values.geth.ports.rpc }}"
    ws_url = "ws://{{ .Values.geth.name }}-replica-service:{{ .Values.geth.ports.ws }}"
    max_rps = 10
    max_ws_conns = 5

    [backend_groups]
    [backend_groups.sequencer]
    backends = ["sequencer"]
    [backend_groups.main]
    backends = ["replicas"]

    # [authentication]
    # secret = "test" 

    [rpc_method_mappings]
    eth_sendTransaction = "sequencer"         # Send directly to sequencer
    eth_sendRawTransaction = "sequencer"      # Transaction submission
    eth_syncing = "sequencer"                 # Sync status
    net_peerCount = "sequencer"               # Node status info
    eth_call = "main"                         # Route to main group
    eth_chainId = "main"                      # Route to main group
    eth_getBalance = "main"                   # Balance queries across all
    eth_getTransactionByHash = "main"         # Transaction retrieval
    eth_getBlockByNumber = "main"             # Block retrieval
    eth_blockNumber = "main"                  # Block number