apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxyd.name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.proxyd.name }}
  ports:
    - name: rpc
      port: {{ .Values.proxyd.ports.rpc }}
      targetPort: {{ .Values.proxyd.ports.rpc }}
    - name: ws
      port: {{ .Values.proxyd.ports.ws }}
      targetPort: {{ .Values.proxyd.ports.ws }}